spring.application.name=burnout-system

# ? Live Cloud MySQL Configuration (Aiven.io Connected)
spring.datasource.url=jdbc:mysql://mysql-1688037b-ajeetsingh-3ea8.l.aivencloud.com:28826/defaultdb?ssl-mode=REQUIRED&sessionVariables=FOREIGN_KEY_CHECKS=0
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_5Q9bX_aYXF5YGSR8i0E

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Port Number
server.port=9090

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Real Email Notification Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ajeet.singh896036@gmail.com
spring.mail.password=opcd rdft dsog toon
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true